// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;
using ML.MLWebApi.Services;
using ML_MLTraining;

// Configure app
var builder = WebApplication.CreateBuilder(args);

// Add controllers
builder.Services.AddControllers();

// Register services
builder.Services.AddScoped<IPredictService, PredictService>();

// Get the model file path from the MLTraining project
var modelPath = Path.Combine(builder.Environment.ContentRootPath, "..", "ML.MLTraining", "MLModel1.mlnet");

builder.Services.AddPredictionEnginePool<MLModel1.ModelInput, MLModel1.ModelOutput>()
    .FromFile(modelPath);

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
});

var app = builder.Build();

app.UseSwagger();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
    });
}

// Map controllers
app.MapControllers();

// Run app
app.Run();
