// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Transforms;

namespace ML_MLTraining
{
    public partial class MLDropoutRisk
    {
        public const string RetrainFilePath =  @"C:\Users\Christian\Downloads\student_mental_health_burnout_1M.csv";
        public const char RetrainSeparatorChar = ',';
        public const bool RetrainHasHeader =  true;
        public const bool RetrainAllowQuoting =  false;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader, bool allowQuoting = RetrainAllowQuoting)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader, allowQuoting);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader, bool allowQuoting)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader, allowQuoting: allowQuoting);
        }


        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrain model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"gender", @"gender"),new InputOutputColumnPair(@"risk_level", @"risk_level")}, outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"age", @"age"),new InputOutputColumnPair(@"academic_year", @"academic_year"),new InputOutputColumnPair(@"study_hours_per_day", @"study_hours_per_day"),new InputOutputColumnPair(@"exam_pressure", @"exam_pressure"),new InputOutputColumnPair(@"academic_performance", @"academic_performance"),new InputOutputColumnPair(@"stress_level", @"stress_level"),new InputOutputColumnPair(@"anxiety_score", @"anxiety_score"),new InputOutputColumnPair(@"depression_score", @"depression_score"),new InputOutputColumnPair(@"sleep_hours", @"sleep_hours"),new InputOutputColumnPair(@"physical_activity", @"physical_activity"),new InputOutputColumnPair(@"social_support", @"social_support"),new InputOutputColumnPair(@"screen_time", @"screen_time"),new InputOutputColumnPair(@"internet_usage", @"internet_usage"),new InputOutputColumnPair(@"financial_stress", @"financial_stress"),new InputOutputColumnPair(@"family_expectation", @"family_expectation"),new InputOutputColumnPair(@"burnout_score", @"burnout_score"),new InputOutputColumnPair(@"mental_health_index", @"mental_health_index")}))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"gender",@"risk_level",@"age",@"academic_year",@"study_hours_per_day",@"exam_pressure",@"academic_performance",@"stress_level",@"anxiety_score",@"depression_score",@"sleep_hours",@"physical_activity",@"social_support",@"screen_time",@"internet_usage",@"financial_stress",@"family_expectation",@"burnout_score",@"mental_health_index"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=4,NumberOfIterations=1129,MinimumExampleCountPerLeaf=28,LearningRate=0.06504369835864175,LabelColumnName=@"dropout_risk",FeatureColumnName=@"Features",Booster=new GradientBooster.Options(){SubsampleFraction=0.6648195462777373,FeatureFraction=0.9673280571602861,L1Regularization=2E-10,L2Regularization=0.07437969285302277},MaximumBinCountPerFeature=307}));

            return pipeline;
        }
    }
 }
