// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ML_MLTraining
{
    public partial class MLMentalHealth
    {
        /// <summary>
        /// model input class for MLMentalHealth.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"age")]
            public float Age { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"gender")]
            public string Gender { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"academic_year")]
            public float Academic_year { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"study_hours_per_day")]
            public float Study_hours_per_day { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"exam_pressure")]
            public float Exam_pressure { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"academic_performance")]
            public float Academic_performance { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"stress_level")]
            public float Stress_level { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"anxiety_score")]
            public float Anxiety_score { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"depression_score")]
            public float Depression_score { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"sleep_hours")]
            public float Sleep_hours { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"physical_activity")]
            public float Physical_activity { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"social_support")]
            public float Social_support { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"screen_time")]
            public float Screen_time { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"internet_usage")]
            public float Internet_usage { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"financial_stress")]
            public float Financial_stress { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"family_expectation")]
            public float Family_expectation { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"mental_health_index")]
            public float Mental_health_index { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLMentalHealth.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"age")]
            public float Age { get; set; }

            [ColumnName(@"gender")]
            public float[] Gender { get; set; }

            [ColumnName(@"academic_year")]
            public float Academic_year { get; set; }

            [ColumnName(@"study_hours_per_day")]
            public float Study_hours_per_day { get; set; }

            [ColumnName(@"exam_pressure")]
            public float Exam_pressure { get; set; }

            [ColumnName(@"academic_performance")]
            public float Academic_performance { get; set; }

            [ColumnName(@"stress_level")]
            public float Stress_level { get; set; }

            [ColumnName(@"anxiety_score")]
            public float Anxiety_score { get; set; }

            [ColumnName(@"depression_score")]
            public float Depression_score { get; set; }

            [ColumnName(@"sleep_hours")]
            public float Sleep_hours { get; set; }

            [ColumnName(@"physical_activity")]
            public float Physical_activity { get; set; }

            [ColumnName(@"social_support")]
            public float Social_support { get; set; }

            [ColumnName(@"screen_time")]
            public float Screen_time { get; set; }

            [ColumnName(@"internet_usage")]
            public float Internet_usage { get; set; }

            [ColumnName(@"financial_stress")]
            public float Financial_stress { get; set; }

            [ColumnName(@"family_expectation")]
            public float Family_expectation { get; set; }

            [ColumnName(@"mental_health_index")]
            public float Mental_health_index { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLMentalHealth.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
